"""add_merchant_field_to_transactions

Revision ID: 160439be825f
Revises: 0fe176d690c4
Create Date: 2025-08-17 16:25:43.001614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160439be825f'
down_revision: Union[str, Sequence[str], None] = '0fe176d690c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('merchant', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_merchant'), 'transactions', ['merchant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_merchant'), table_name='transactions')
    op.drop_column('transactions', 'merchant')
    # ### end Alembic commands ###
