"""add transaction_type to transactions

Revision ID: 5db90bdcac9f
Revises: 3ad82e4564fe
Create Date: 2025-08-02 12:18:28.189952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db90bdcac9f'
down_revision: Union[str, Sequence[str], None] = '3ad82e4564fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'budgets', ['id'])
    op.create_unique_constraint(None, 'insights', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insights', type_='unique')
    op.drop_constraint(None, 'budgets', type_='unique')
    # ### end Alembic commands ###
